dist: trusty
sudo: required
language: go

go:
- 1.9.x
- 1.10.x
- master

env:
- MYSQL_IMAGE=mysql/mysql-server:5.5
- MYSQL_IMAGE=mysql/mysql-server:5.6
- MYSQL_IMAGE=mysql/mysql-server:5.7
- MYSQL_IMAGE=mysql/mysql-server:8.0
- MYSQL_IMAGE=percona/percona-server:5.5
- MYSQL_IMAGE=percona/percona-server:5.6
- MYSQL_IMAGE=percona/percona-server:5.7

services:
- docker

go_import_path: github.com/percona/mysqld_exporter

before_script:
- sudo service mysql stop
- docker --version
- docker-compose --version
- docker-compose up -d

script:
- make
- make test

notifications:
  email: false
