dist: trusty
sudo: required
language: go

# Whenever the Go version is updated here, .circleci/config.yml and .promu.yml
# should also be updated.
go:
- 1.12.x

env:
- MYSQL_IMAGE=mysql/mysql-server:5.5
- MYSQL_IMAGE=mysql/mysql-server:5.6
- MYSQL_IMAGE=mysql/mysql-server:5.7
- MYSQL_IMAGE=mysql/mysql-server:8.0
- MYSQL_IMAGE=mariadb:5
- MYSQL_IMAGE=mariadb:10.0
- MYSQL_IMAGE=mariadb:10.1
- MYSQL_IMAGE=mariadb:10.2
- MYSQL_IMAGE=mariadb:10.3

services:
- docker

go_import_path: github.com/prometheus/mysqld_exporter

before_script:
- sudo service mysql stop
- docker --version
- docker-compose --version
- docker-compose up -d

script:
- make build
- make test
